### PR TITLE
removed permission_handler dependency

### PR DESCRIPTION
**Pull request by meeefiu**

### CODE REVIEW

**Comment by beygee** [comment]
I'll check it is OK without `permission_handler`

**Comment by beygee** [comment]
It need to access external storage to detect screenshot on android. So It is not appropriate to remove it.

**Comment by fatherOfLegends** [comment]
Please accept this change. Just because you need a permission does not mean you need to bake the permission_handler into your plugin. It makes it unusable for many.

**Comment by CaleyD** [comment]
I'm running into the same issue - I cannot integrate this into my app due to this.

**Pull request merged**
